export const Action = {
  ATTEMPT_LOGIN: 'ATTEMPT_LOGIN',
  ATTEMPT_LOGOUT: 'ATTEMPT_LOGOUT',
  CLEAR_DATA: 'CLEAR_DATA',
  CHANGE_CONVERSION_TYPE: 'CHANGE_CONVERSION_TYPE',
  SET_BIDS: 'SET_BIDS',
};
